source("pages/food_card.R")

all_ui <- function() {
  div(
    food_card("add_brocolli", "Frozen Broccoli", "brocolli.jpg"),
    food_card("add_carrot", "Carrots, Raw", "carrot.jpg"),
    food_card("add_celery", "Celery, Raw", "celery.jpg"),
    food_card("add_corn", "Frozen Corn", "corn.jpg"),
    food_card("add_lettuce", "Lettuce, Iceberg, Raw", "lettuce.jpg"),
    food_card("add_potato", "Potatoes, Baked", "potato.jpg"),
    food_card("add_tofu", "Tofu", "tofu.jpg"),
    food_card("add_roasted_chicken", "Roasted Chicken", "brocolli.jpg"),
    food_card("add_bologna", "Bologna, Turkey", "brocolli.jpg"),
    food_card("add_frankfurter", "Frankfurter, Beef", "brocolli.jpg"),
    food_card("add_ham", "Ham, Sliced, Extralean", "brocolli.jpg"),
    food_card("add_kielbasa", "Kielbasa, Prk", "brocolli.jpg"),
    food_card("add_pork", "Pork", "brocolli.jpg"),
    food_card("add_sardines", "Sardines in Oil", "brocolli.jpg"),
    food_card("add_tuna", "White Tuna in Water", "brocolli.jpg"),
    food_card("add_hamburger", "Hamburger W/Toppings", "brocolli.jpg"),
    food_card("add_hotdog", "Hotdog, Plain", "brocolli.jpg"),
    food_card("add_pepper", "Peppers, Sweet, Raw", "brocolli.jpg"),
    food_card("add_tomato", "Tomato, Red, Ripe, Raw", "brocolli.jpg"),
    food_card("add_apple", "Apple, Raw, W/Skin", "brocolli.jpg"),
    food_card("add_banana", "Banana", "brocolli.jpg"),
    food_card("add_grapes", "Grapes", "brocolli.jpg"),
    food_card("add_kiwi", "Kiwifruit, Raw, Fresh", "brocolli.jpg"),
    food_card("add_orange", "Oranges", "brocolli.jpg"),
    food_card("add_apple_pie", "Apple Pie", "brocolli.jpg"),
    food_card("add_butter", "Butter, Regular", "brocolli.jpg"),
    food_card("add_cheddar", "Cheddar Cheese", "brocolli.jpg"),
    food_card("add_whole_milk", "3.3% Fat, Whole Milk", "brocolli.jpg"),
    food_card("add_lowfat_milk", "2% Lowfat Milk", "brocolli.jpg"),
    food_card("add_skim_milk", "Skim Milk", "brocolli.jpg"),
    food_card("add_poach_eggs", "Poached Eggs", "brocolli.jpg"),
    food_card("add_scrambled_eggs", "Scrambled Eggs", "brocolli.jpg"),
    food_card("add_chicknoodle_soup", "Chicken Noodle Soup", "brocolli.jpg"),
    food_card("add_spltpeaham_soup", "Split Pea & Ham Soup", "brocolli.jpg"),
    food_card("add_vegetbeef_soup", "Vegetable Beef Soup", "brocolli.jpg"),
    food_card("add_neweng_clamchwd", "New England Clam Chowder Soup", "brocolli.jpg"),
    food_card("add_tomato_soup", "Tomato Soup", "brocolli.jpg"),
    food_card("add_neclamchwd_wmilk", "New England Clam Chowder Soup W/ Milk", "brocolli.jpg"),
    food_card("add_crmmshrm_wmilk", "Cream of Mushroom Soup W/ Milk", "brocolli.jpg"),
    food_card("add_beanbacn_soup", "Bean Bacon Soup W/ Water", "brocolli.jpg"),
    food_card("add_bagel", "Bagels", "brocolli.jpg"),
    food_card("add_wheat_bread", "Wheat Bread", "brocolli.jpg"),
    food_card("add_white_bread", "White Bread", "brocolli.jpg"),
    food_card("add_oatmeal_cookies", "Oatmeal Cookies", "brocolli.jpg"),
    food_card("add_apple_pie", "Apple Pie", "brocolli.jpg"),
    food_card("add_chocochip_cookies", "Chocolate Chip Cookies", "brocolli.jpg"),
    food_card("add_capn_crunch", "Cap'N Crunch", "brocolli.jpg"),
    food_card("add_cheerios", "Cheerios", "brocolli.jpg"),
    food_card("add_cornflks_kelloggs", "Corn Flakes, Kellogg's", "brocolli.jpg"),
    food_card("add_raisinbrn_kelloggs", "Raisin Bran Kelloggs", "brocolli.jpg"),
    food_card("add_rice_krispies", "Rice Krispies", "brocolli.jpg"),
    food_card("add_special_k", "Special K", "brocolli.jpg"),
    food_card("add_oatmeal", "Oatmeal", "brocolli.jpg"),
    food_card("add_maltomeal", "Malt-O-Meal, Choco", "brocolli.jpg"),
    food_card("add_couscous", "Couscous", "brocolli.jpg"),
    food_card("add_white_rice", "White Rice", "brocolli.jpg"),
    food_card("add_macaroni", "Macaroni, Cooked", "brocolli.jpg"),
    food_card("add_tortilla", "Tortilla Chip", "brocolli.jpg"),
    food_card("add_oatmeal", "Oatmeal", "brocolli.jpg"),
    food_card("add_spaghetti", "Spaghetti W/ Sauce", "brocolli.jpg"),
    food_card("add_pizza", "Pizza W/ Pepperoni", "brocolli.jpg"),
    food_card("add_taco", "Taco", "brocolli.jpg"),
    food_card("add_hamburger", "Hamburger W/ Toppings", "brocolli.jpg"),
    food_card("add_hotdog", "Hotdog, Plain", "brocolli.jpg"),
    food_card("add_rice_krispies", "Rice Krispies", "brocolli.jpg"),
    food_card("add_special_k", "Special K", "brocolli.jpg"),
    food_card("add_peanut_butter", "Peanut Butter", "brocolli.jpg"),
    food_card("add_popcorn", "Popcorn, Air-Popped", "brocolli.jpg"),
    food_card("add_potato_chips", "Potato Chips, BBQ flavor", "brocolli.jpg"),
    food_card("add_pretzels", "Pretzels", "brocolli.jpg"),
    food_card("add_tortilla", "Tortilla Chip", "brocolli.jpg"),
  )
}